var data = [
  {
    id: '1',
    parentId: '0',
    parentTitle: '',
    blogData: {
      title: 'React',
      banner: 'https://picsum.photos/1400/200',
      body: 'React is a framework called React. It is called React because the person who named the framework decided it should be called React. We will  talk more about react in the subblogs',
      tagString: 'ASDF|QWER',
    },
    childIds: ['2', '3'],
    type: 'topic',
  },
  {
    id: '2',
    parentId: '1',
    parentTitle: 'React',
    blogData: {
      title: 'React doc one ',
      banner: 'https://picsum.photos/1400/200',
      body: 'React is a framework called React as we saw in the first article. This Article is called React doc one because the person who named it decided to name it as React doc one',
      Tags_string: 'ASDF|QWER',
    },
    childIds: [],
    type: 'blog',
  },
  {
    id: '3',
    parentId: '1',
    parentTitle: 'React',
    blogData: {
      title: 'React doc two',
      banner: 'https://picsum.photos/1400/200',
      body: 'React is a framework called React as we saw in the first article. This Article is called React doc two because one was taken',
      Tags_string: 'ASDF|QWER',
    },
    childIds: [],
    type: 'blog',
  },
  {
    id: '4',
    parentId: '0',
    parentTitle: '',
    blogData: {
      title: 'Angular',
      banner: 'https://picsum.photos/1400/200',
      body: 'Angular is a framework called Angular. It is called Angular because the person who named the framework decided it should be called Angular. We will  talk more about react in the subblogs',
      tagString: 'ASDF|QWER',
    },
    childIds: ['5', '6', '7'],
    type: 'topic',
  },
  {
    id: '5',
    parentId: '4',
    parentTitle: 'Angular',
    blogData: {
      title: 'Angular doc one',
      banner: 'https://picsum.photos/1400/200',
      body: 'Angular is a framework called Angular as we saw in the first article. This Article is called Angular doc one because the person who named it decided to name it as Angular doc one',
      Tags_string: 'ASDF|QWER',
    },
    childIds: [],
    type: 'blog',
  },
  {
    id: '6',
    parentId: '4',
    parentTitle: 'Angular',
    blogData: {
      title: 'Angular doc two',
      banner: 'https://picsum.photos/1400/200',
      body: 'Angular is a framework called Angular as we saw in the first article. This Article is called Angular doc two because one was taken',
      Tags_string: 'ASDF|QWER',
    },
    childIds: [],
    type: 'blog',
  },
  {
    id: '7',
    parentId: '4',
    parentTitle: 'Angular',
    blogData: {
      title: 'Angular doc four',
      banner: 'https://picsum.photos/1400/200',
      body: 'Angular is a framework called Angular as we saw in the first article. This Article is called Angular doc four because one and two were taken but I the author have chosen to ignore the number three because it sounds like tree',
      Tags_string: 'ASDF|QWER',
    },
    childIds: [],
    type: 'blog',
  },
  {
    id: '8',
    parentId: '0',
    parentTitle: '',
    blogData: {
      title: 'French Fries',
      banner: 'https://picsum.photos/1400/200',
      body: 'There is nothing to learn here, I am just more fun than every one above me :D',
      tagString: 'ASDF|QWER',
    },
    childIds: [],
    type: 'topic',
  },
  {
    id: '9',
    parentId: '8',
    parentTitle: 'French Fries',
    blogData: {
      title: 'Honey Chilli Fries',
      banner: 'https://picsum.photos/1400/200',
      body: 'Likewise, I am just more fun than everything above me :D',
      tagString: 'ASDF|QWER',
    },
    childIds: [],
    type: 'blog',
  },
  {
    id: '10',
    parentId: '8',
    parentTitle: 'French Fries',
    blogData: {
      title: 'Beer',
      banner: 'https://picsum.photos/1400/200',
      body: 'Hold my beer!',
      tagString: 'ASDF|QWER',
    },
    childIds: [],
    type: 'blog',
  },
];

export default data;
